# To build the entire stack run 'make run'

services:
  crystal-base-template:
    container_name: crystal-base-template
    restart: "no" # unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CRYSTAL_VERSION=${CRYSTAL_VERSION}
    # ports:
    #   - 8080:8080
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 15s
