#!/bin/bash

source script/setup-env $@

# start and background the server process
echo -e "🚀 ${BLUE}starting the server${OFF}"

# Start the Crystal server in the background
crystal run spec/acceptance/server.cr &

# Get the PID of the background process
SERVER_PID=$!

# Define a function to kill the background process
cleanup() {
  echo "Killing background process..."
  kill $SERVER_PID
}

# Set the trap to call the cleanup function on script exit
trap cleanup EXIT

# run the tests
echo -e "🧪 ${BLUE}running the acceptance tests${OFF}"
crystal run spec/acceptance/tests.cr

# Wait for the background process to finish (if needed)
wait $SERVER_PID
