#!/bin/bash

set -e

source script/setup-env $@

KCOV_BIN="kcov"

if [[ -f "$DIR/bin/kcov" && "$CI" == "true" ]]; then
  KCOV_BIN="$DIR/bin/kcov"
fi

# check to ensure both crystal and shards are installed
if ! [ -x "$(command -v $KCOV_BIN)" ]; then
  echo -e "❌ ${RED}Error${OFF}: kcov is not installed"
  echo "Please install kcov to use code coverage reports:"
  echo " - macOS: https://formulae.brew.sh/formula/kcov"
  echo " - other: https://github.com/SimonKagstrom/kcov/blob/c71d42f1cadddbd2da38c1101d71ef2b84065c7b/INSTALL.md"
  exit 1
fi

# only build the require_spec binary if it's not already built
if [ ! -f "$DIR/bin/require_spec" ]; then
  echo "building require_spec binary..."
  crystal build "$DIR/script/require_spec.cr" -D skip-integration -o "$DIR/bin/require_spec" --exclude-warnings $SHARDS_INSTALL_PATH
fi

$KCOV_BIN --clean --include-path=$DIR/src "$DIR/coverage" "$DIR/bin/require_spec"

CRYSTAL_OPTS="" crystal tool unreachable "$DIR/script/require_spec.cr" --check
