#!/bin/bash

set -e

source script/setup-env $@

KCOV_BIN="kcov"

if [[ -f "$DIR/bin/kcov" && "$CI" == "true" ]]; then
  KCOV_BIN="$DIR/bin/kcov"
fi

# check to ensure both crystal and shards are installed
if ! [ -x "$(command -v $KCOV_BIN)" ]; then
  echo -e "❌ ${RED}Error${OFF}: kcov is not installed"
  echo "Please install kcov to use code coverage reports:"
  echo " - macOS: https://formulae.brew.sh/formula/kcov"
  echo " - other: https://github.com/SimonKagstrom/kcov/blob/c71d42f1cadddbd2da38c1101d71ef2b84065c7b/INSTALL.md"
  exit 1
fi

crystal build "$DIR/script/require_spec.cr" -D skip-integration -o "$DIR/bin/require_spec" --exclude-warnings $SHARDS_INSTALL_PATH

if [ -d "$DIR/coverage" ]; then
  rm -rf "$DIR/coverage"
fi

mkdir -p "$DIR/coverage"

$KCOV_BIN --clean --include-path=$DIR/src "$DIR/coverage" "$DIR/bin/require_spec"

coverage=0

# grep index.js for "covered":"100.0" to check if all files have 100% coverage
if grep -q '"covered":"100.0"' "$DIR/coverage/index.js"; then
  echo -e "✅ ${GREEN}All files have 100% coverage!${OFF}"
  coverage=0
else
  echo -e "❌ ${RED}Some files do not have 100% coverage!${OFF}"
  coverage=1
fi

CRYSTAL_OPTS="" crystal tool unreachable "$DIR/script/require_spec.cr" --check

exit $coverage
